### PR TITLE
Remove extending the Javascript builtin objects

### LINKED ISSUE #397: Compatibility with Typescript 4.9
Why:

The litegraph library fails to compile with typescript4.9+ in Angular 16. This is because TS isn't aware that we extended a bult-in  DOM object prototype.

Changes to address this issue:

* Remove extending the Math & CanvasRenderingContext2D classes. It was messing up the typescript 4.9+
* Use utility classes instead of that extended functionality
* Add some type corrections in litegraph.d.ts
* Fix a couple of build issues

Optional details:

```diff
- ctx.roundRect(margin, y, widget_width - margin * 2, H, [H * 0.5]);
+ LCTXUtil.roundRect(ctx, margin, y, widget_width - margin * 2, H, [H * 0.5]);
```

I'd open an MR with the changes listed in this [pull request](https://github.com/InamataCo/litegraph.js/pull/6/files) if it sounds acceptable.

The error we get is 
```
Error: node_modules/typescript/lib/lib.dom.d.ts:3654:11 - error TS2430: Interface 'CanvasRenderingContext2D' incorrectly extends interface 'CanvasPath'.
  Types of property 'roundRect' are incompatible.
    Type '(x: number, y: number, width: number, height: number, radius: number, radiusLow: number) => void' is not assignable to type '(x: number, y: number, w: number, h: number, radii?: number | DOMPointInit | (number | DOMPointInit)[] | undefined) => void'.

3654 interface CanvasRenderingContext2D extends CanvasCompositing, CanvasDrawImage, CanvasDrawPath, CanvasFillStrokeStyles, CanvasFilters, CanvasImageData, CanvasImageSmoothing, CanvasPath, CanvasPathDrawingStyles, CanvasRect, CanvasShadowStyles, CanvasState, CanvasText, CanvasTextDrawingStyles, CanvasTransform, CanvasUserInterface {
     
```

### PR DESCRIPTION
**Pull request by moritz89**
* Remove extending the Math & CanvasRenderingContext2D classes. It was messing up the typescript 4.9+
* Use utility classes instead of that extended functionality
* Add some type corrections in litegraph.d.ts
* Fix a couple of build issues

Closes #397

### CODE REVIEW

**Comment by jagenjo** [comment]
Sorry, I cant accept this one.
The function roundRect is available in CanvasContext latest versions, it was added when it wasnt available.
But LiteGraph must be compatible with another library called Canvas2DtoWebGL and in that one I overwrite the function.

In other words, rendering functions should be associated with the rendering context, so no matter which one you use (Canvas2D, or WebGL) the function works the same.

**Comment by moritz89** [comment]
Had to change `Math.clamp` to `LMathUtil.clamp` in editor/js/libs/litegl.js but since it used an old encoding, ISO-8859, instead of unicode / utf-8, it resulted in a full file diff.

**Comment by jagenjo** [comment]
the problem is that litegl comes from other repo, which I may update in the future with other changes.

I recommend that you kill LMathUtils and define a global clamp function, way easier.

**Comment by jagenjo** [comment]
just one final change, instead of:

global.clamp = function(...)

can you do it this way?

function clamp(...);
global.clamp = clamp;

This way function retains name.

**Comment by moritz89** [comment]
Good point

**Comment by jagenjo** [comment]
:)
