### ISSUE TITLE
Compatibility with Typescript 4.9

### ISSUE THREAD

**Issue by moritz89** [jagenjo/litegraph.js#397]
Why:

The litegraph library fails to compile with typescript4.9+ in Angular 16. This is because TS isn't aware that we extended a bult-in  DOM object prototype.

Changes to address this issue:

* Remove extending the Math & CanvasRenderingContext2D classes. It was messing up the typescript 4.9+
* Use utility classes instead of that extended functionality
* Add some type corrections in litegraph.d.ts
* Fix a couple of build issues

Optional details:

```diff
- ctx.roundRect(margin, y, widget_width - margin * 2, H, [H * 0.5]);
+ LCTXUtil.roundRect(ctx, margin, y, widget_width - margin * 2, H, [H * 0.5]);
```

I'd open an MR with the changes listed in this [pull request](https://github.com/InamataCo/litegraph.js/pull/6/files) if it sounds acceptable.

The error we get is 
```
Error: node_modules/typescript/lib/lib.dom.d.ts:3654:11 - error TS2430: Interface 'CanvasRenderingContext2D' incorrectly extends interface 'CanvasPath'.
  Types of property 'roundRect' are incompatible.
    Type '(x: number, y: number, width: number, height: number, radius: number, radiusLow: number) => void' is not assignable to type '(x: number, y: number, w: number, h: number, radii?: number | DOMPointInit | (number | DOMPointInit)[] | undefined) => void'.

3654 interface CanvasRenderingContext2D extends CanvasCompositing, CanvasDrawImage, CanvasDrawPath, CanvasFillStrokeStyles, CanvasFilters, CanvasImageData, CanvasImageSmoothing, CanvasPath, CanvasPathDrawingStyles, CanvasRect, CanvasShadowStyles, CanvasState, CanvasText, CanvasTextDrawingStyles, CanvasTransform, CanvasUserInterface {
     
```

**Comment by moritz89** [comment]
@atlasan I opened MR #401 to address this issue

**Comment by jagenjo** [comment]
roundRect is a supported function in latest versions:

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/roundRect

It was added long before it was supported, so it could be removed AFAIK.

**Comment by moritz89** [comment]
There is a slight difference in the method signature (radiusLow), but I'll check if existing code can be ported. The built-in function can support existing intentions as the radii parameter allows specifying each corner's radius.

**Comment by jagenjo** [comment]
I did a proposal to change the spec some years ago and they accepted it so it is compatible with this function.
